- encabezado:
    texto: Grado en Educaci칩n Infantil
    imagen: https://www.uchceu.es/img/estudios/grado/cabeceras/educacion-magisterio.jpg
    slogan: texto del slogan
    sector1:
      - columnas:
        texto: texto columna 1
        texto: texto columna 2
        texto: texto columna 3
  salida_profesional:
    titulo: Salida Profesional
    - parrafo:
      texto: texto p치rrafo 1
      texto: texto p치rrafo 2
      texto: texto p치rrafo 3
    - items:
      texto: texto item 1
      texto: texto item 2
      texto: texto item 3
